name: Deployment Workflow
on: push
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Download code
              uses: actions/checkout@v4
            - name: Install dependencies
              run: npm ci
            - name: Lint
              run: npm run lint
            - name: Test
              run: npm test
            - name: Build
              run: npm run build
            - name: Deploy
              run: echo "Done!!"
